
book = "The Trial"
author = "Franz Kafka"
blink = "http://www.amazon.com/exec/obidos/ASIN/0805210407/qid=1013512068/sr=8-2/ref=sr_8_67_2/104-3412157-4261534"

b2link="http://www.amazon.com/exec/obidos/ASIN/038519286X/qid=1013652908/sr=8-1/ref=sr_8_7_1/104-3412157-4261534"

b3link="http://www.thebigo.com/pages/book/book.html"

song = "While My Guitar Gently Weeps"
band = "The Beatles"
slink = "(Beatles)-While My Guitar Gently Weeps.mp3"

arts4a="<table><tr><td><center><b><u>Current Favourite Song</u></b><br> <A href='"+slink+"'>"+song+"</a><br> by "+band+"</td><td><center>|<br>|<br>|</td><td><centeR><u><b>Current Book Being Read</b></u><br> <a href='"+blink+"' target='right'>"+book+"</a><br> by "+author+"</td></tr></table>"


