a="One of my favorite websites(portals) is <a href='http://www.camwhores.com'>here</a>. where there are some decent chics, and interesting times."
aon=0
b="LOL, and i don't do that much, but this is a wonderful site: <a href='http://www.whowouldbuythat.com'>Who would buy THAT?</a> has all the oddest ebay auctions you'll ever come across. Check it out, it is hillarious."
bon=0
c="<A href='http://www.angelfire.com/rock/scuzzpuck/'>This</a> is a great site. Mr. T vs Judge Dredd! Check it out."
con=0
d="<a href='http://www.lanminds.com/explore/sheath.html'>Sheath File</a> Just take a peek, it only takes a second, then you can hitthe back button and see other cool things."
don=0
e="<a href='http://www.leon.nano.pl/integrale/script1_e.shtml'>Leon-The Professional</a> or as you know it simply 'The Professional'.  There were 30 minutes of deleted scenes from teh version you've seen.  This is the link to the script form those scenes, and they make the movie better for sure."
eon=0
f="This is <a href='http://www.project-mayhem.ndo.co.uk/'>Project Mayhem</a>. Go and learn, i do the homework asignments from time to time. My favorite one is putting out of order signs on doors. Expecially all the doors to a building and watch people really struggle."
fon=0
g="<a href='http://www.hotornot.com'>Hot or Not?</a> This is really a great site, you go and rate peoples appearance and you can post your own or your friends (enemies?). The link to mine is <a href='http://www.amihotornot.com/r/?eid=KUNENZ&key=QBU'>here</a>!"
gon=0
h="<a href='http://www.geocities.com/Athens/Academy/1974/index.html'>Nadsat</a> Nadsat translator, the owner hasn't updated his site in a while, but it is still a bolshy program. Now i am ittying to itty firegold moloko and shvat drencrom with my droogs"
hon=0
i="<a href='http://www.amithebomb.com'>Am i the Bomb?</a> Same as above, accept you leave comments too, and more regulation meaning hotter chics"
ion=0
j="This <a href='http://www.telefragged.com/Cybertron/index.htm'>Site</a> is just a pimp ass thing. These great minds have taken quake 2, which i think pretty much sucked and changed all the characters to Transformers charaters. All the things are still in beta, but they have awesome 3-d renderings all over the place and a working beta version. I think if this was better known, it would take off, so SPREAD THE WORD MO FO!"
jon=0
k="I almost forgot <a href='http://www.gurlpages.com/me/jage/mellow.html'>JJ's</a> page. Yeah, it's linked, nouf said. Although aparently there is some picture of some chic named kelly on there taht i'm supposed ot see. if YOU find it, then i'll give you a prize."
kon=0
l="<a href='http://www.gigahosts.com/ballericons/'>Ballericons</a> habe the BEST icons for AIM around, they are hilarious, but i like my DaMour (kefka) icon better."
lon=0
m="Genes in my family are strong. At least i'll claim they are. Check out the distant relative's take on <a href='http://online.itp.ucsb.edu/online/colloq/damour1/'>gravity</a>."
mon=0
n="<a href='http://www.colorado.edu/physics/2000/waves_particles/wavpart2.html'>Physics Applets</a> at this site are just awesome and VERY informative. Check this one out, then surf aroudn teh site ot find others. You can learn a lot about the scientific world about you at this site."
non=0
o="<a href='http://www.meru.org/Codes/satinovr.html'>Divine Authorship?</a> The torah (first five books of the bible) have some strange mysteries surrounding them, check it out."
oon=0
p="<a href='http://www.artobello.de/Kundera/index.html'>Milan Kundera</a> is the god of authorship, and this is the best (only?) sight dedicated to him."
pon=0
q="My cousin's <a href='http://www.geocities.com/e_sarb/coolpage.html'>Old Page</a> | <a href='http://www.geocities.com/bachor_net/'>New Page</a>, the former is a good first page, but he just learned html so bear with him, ok! The later is better, but when you see it you'll understand my butt, i mean aber, i mean mais, i mean BUT"
qon=0
r="This is the <a href='http://www.emode.com/emode/ultimate.jsp'>Ultimate Personality Test</a> you take it and put your froends email init, adn you get comparison percentages, my email is <a href='mailto:damour@pilot.msu.edu'>damour@pilot.msu.edu</a>"
ron=0
s="<a href='http://www.msu.edu/~wrigh131/'>Quotes of the Exsdess</a> another friend's, i'm going to make him put up the quotes in wav format, then laughter will really begin."
son=0
t="<a href='http://www.msu.edu/~rahmanse/'>XXXYYY</a>Pending Construction! But check it all the same, might as well, got nothing better to do."
ton=0
u="<a href='http://www.gameboomers.com/wtcheats/pcIi/IncredMach2.htm'>Solutions</a> to the incredible machine game. Never played, <a href='aim:goim?screenname=digitydope&message=I+want+the+incredible+machine'>im</a> me, i'll find it somewhere, i promise. I Think i have it."
uon=0
v="My <a href='http://hometown.aol.com/slacer752/index.html'>Neighbor / 'Homies'</a> Webpage, it needs work. He used aol to make it...."
von=0
w="Want full simpsons episodes in realvideo or asf formats. No what about futurama, or movies or daria or some shit like that. Then <a href='http://home.conceptsfa.nl/~taverne/site.htm'>Paul's Zone</a> is yoru hookup. Check it, you'll be happy."
won=0
x="<a href='http://www.enigmus.addr.com/tfgalaxycom/episodes.htm'>Transformers</a> Episodes are all over here, all 98 episodes, i myself am missing 20 of them still, so that's a impresive collection."
xon=0
y="<a href='http://www.msu.edu/~rileymat/'>Matt's Web Presence</a>"
yon=0
z="<a href=http://www.engrish.com/'>Engrish</a>, It's not just for the engrish anymore!<br>"
zon=0

